#!/bin/bash
# Safe cleanup script - removes duplicate and unused files
# This script will backup files before deletion

set -e

echo "=========================================="
echo "PROJECT CLEANUP SCRIPT"
echo "=========================================="
echo ""

# Create backup directory
BACKUP_DIR="backup_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
echo "✅ Created backup directory: $BACKUP_DIR"
echo ""

# Function to safely remove a file
safe_remove() {
    local file="$1"
    if [ -f "$file" ]; then
        # Create backup
        mkdir -p "$BACKUP_DIR/$(dirname "$file")"
        cp "$file" "$BACKUP_DIR/$file"
        # Remove file
        rm "$file"
        echo "   ✓ Removed: $file"
    fi
}

echo "📝 Step 1: Removing OLD/DEPRECATED Python files..."
echo "------------------------------------------------"
safe_remove "rag_chatbot.py"
safe_remove "vector_db.py"
safe_remove "app.py"
safe_remove "data_collection.py"
safe_remove "enhanced_data_collection.py"
safe_remove "proper_crawler.py"
safe_remove "crawl_specific_urls.py"
safe_remove "prepare_dataset.py"
safe_remove "prepare_finetuning_dataset.py"
safe_remove "test_system.py"
safe_remove "quick_test.py"
safe_remove "fine_tune.py"
safe_remove "fine_tune_cpu.py"
echo ""

echo "📝 Step 2: Removing OLD shell scripts..."
echo "------------------------------------------------"
safe_remove "build_pipeline.sh"
safe_remove "enhanced_build_pipeline.sh"
safe_remove "auto_complete_pipeline.sh"
safe_remove "setup.sh"
safe_remove "quick_start.sh"
safe_remove "start_chatbot.sh"
safe_remove "start_streamlit.sh"
safe_remove "check_progress.sh"
safe_remove "check_finetuning.sh"
safe_remove "check_vector_build.sh"
echo ""

echo "📝 Step 3: Removing OLD/REDUNDANT data files..."
echo "------------------------------------------------"
safe_remove "data/rackspace_knowledge.json"
safe_remove "data/crawl_statistics.json"
safe_remove "data/rackspace_knowledge.txt"
echo ""

echo "📝 Step 4: Removing LOG files..."
echo "------------------------------------------------"
safe_remove "app_output.log"
safe_remove "data_collection.log"
safe_remove "fine_tune.log"
safe_remove "vector_build.log"
echo ""

echo "📝 Step 5: Removing OUTDATED/REDUNDANT documentation files..."
echo "------------------------------------------------"
safe_remove "BACKEND_API_GUIDE.md"
safe_remove "BEFORE_AFTER_COMPARISON.md"
safe_remove "COLLECTION_SUCCESS_SUMMARY.md"
safe_remove "COMPLETE_SOLUTION.md"
safe_remove "CURRENT_STATUS.md"
safe_remove "DATA_PREPROCESSING_EXPLAINED.md"
safe_remove "EMBEDDINGS_VECTOR_DB_GUIDE.md"
safe_remove "ENHANCED_REBUILD_GUIDE.md"
safe_remove "FINAL_RAG_PIPELINE.md"
safe_remove "FINETUNING_STATUS.md"
safe_remove "FIXES_APPLIED.md"
safe_remove "FRONTEND_UI_GUIDE.md"
safe_remove "GETTING_STARTED.md"
safe_remove "LAUNCH_GUIDE.md"
safe_remove "PROJECT_STRUCTURE.md"
safe_remove "PROPOSED_CHANGES.md"
safe_remove "QUICKSTART.md"
safe_remove "START_HERE.md"
safe_remove "SUMMARY.md"
safe_remove "TEXT_PREPROCESSING_PIPELINE.md"
safe_remove "TRAINING_PROGRESS_REPORT.md"
safe_remove "TRAINING_STARTED.md"
safe_remove "UI_COMPARISON.md"
safe_remove "VISUAL_GUIDE.md"
safe_remove "WHAT_TO_DO_NOW.md"
safe_remove "YOUR_OWN_MODEL.md"
echo ""

echo "=========================================="
echo "✅ CLEANUP COMPLETE!"
echo "=========================================="
echo ""
echo "📊 Summary:"
echo "   - Backup created in: $BACKUP_DIR"
echo "   - Old Python files removed"
echo "   - Old shell scripts removed"
echo "   - Old data files removed"
echo "   - Log files removed"
echo "   - Outdated documentation removed"
echo ""
echo "📁 Files KEPT (essential):"
echo "   - streamlit_app.py (main UI)"
echo "   - enhanced_rag_chatbot.py (core chatbot)"
echo "   - enhanced_vector_db.py (vector DB)"
echo "   - rebuild_rag_system.py (new crawler)"
echo "   - config.py (configuration)"
echo "   - requirements.txt (dependencies)"
echo "   - README.md (main documentation)"
echo "   - FINAL_SYSTEM_STATUS.md (system status)"
echo "   - data/rackspace_knowledge_clean.json (clean data)"
echo "   - data/training_qa_pairs.json (training data)"
echo "   - models/rackspace_finetuned/ (fine-tuned model)"
echo ""
echo "💡 To restore files: cp -r $BACKUP_DIR/* ."
echo ""
